# MongoDB数据源配置
spring:
  data:
    mongodb:
      host: 47.108.148.53
      port: 27017
      database: base_education
    redis:
      host: 127.0.0.1
      port: 6379
      password: myredis
      database: 0









